### ISSUE TITLE
Allow whitelist of hardcoded routes

### ISSUE THREAD

**Issue by lowjoel** [amatsuda/traceroute#16]
Using plataformatec/devise in my project, traceroute shows:

```
$ bundle exec rake traceroute
Unused routes (1):
  #
Unreachable action methods (21):
  devise/confirmations#create
  devise/confirmations#new
  devise/confirmations#show
  devise/omniauth_callbacks#failure
  devise/omniauth_callbacks#passthru
  devise/passwords#create
  devise/passwords#edit
  devise/passwords#new
  devise/passwords#update
  devise/registrations#cancel
  devise/registrations#create
  devise/registrations#destroy
  devise/registrations#edit
  devise/registrations#new
  devise/registrations#update
  devise/sessions#create
  devise/sessions#destroy
  devise/sessions#new
  devise/unlocks#create
  devise/unlocks#new
  devise/unlocks#show
```

Those routes are defined, but are `ActionDispatch::Routing::Mapper::Constraints` and so are removed from the list of defined routes. I can see why because there is a dynamic component to the route definition, but makes the report noisy.

Would it be a good idea to implement some kind of whitelist where the routes are assumed to be present and properly defined?

**Comment by distributedlife** [comment]
Would a blacklist be more useful? A whitelist is "only these routes are ok", this goes against the nature of the gem to detect accidents. A blacklist would let us to say "don't report on these specific routes". 

I ask because I'm putting together a PR for blacklist support.

**Comment by lowjoel** [comment]
Okay I think my whitelist and your blacklist is the same thing... probably it's flipsides of the same coin :P

**Comment by distributedlife** [comment]
Hey @lowjoel would this fork: https://github.com/distributedlife/traceroute work? We're trying it on a project now to see if it works. If you also think it'll be useful, I will submit a PR to this repo.

**Comment by lowjoel** [comment]
@distributedlife sorry, been too busy.

It looks good, but it needs to handle the case where:
 - traceroute.yml is empty (`NoMethodError: undefined method `has_key?' for false:FalseClass`)
 - key is defined to empty (`NoMethodError: undefined method `each' for nil:NilClass`)

Otherwise, running the rake task tells me I have too many problematic routes! Thanks!

**Comment by distributedlife** [comment]
I've pushed fixes for those two.

**Comment by amatsuda** [comment]
Done via #20
