### ISSUE TITLE
Where is the License?

### ISSUE THREAD

**Issue by JoaoGFarias** [amatsuda/traceroute#23]
The README talks about the LICENSE.txt.
Where is it located?

**Comment by david-a-wheeler** [comment]
The file "traceroute.gemspec" states that the license is MIT, but I'd still really like to see an actual LICENSE file.

**Comment by amatsuda** [comment]
Just added the license file at 0017add2cc0cddef06a3712ce2a53d71a42d3da9. Thanks!
