### ISSUE TITLE
Does not work with Rails 6.

### ISSUE THREAD

**Issue by 6temes** [amatsuda/traceroute#36]
All routes appear as unused.

**Comment by alphabt** [comment]
Same here, having the same issue with Rails 6.0.0.

**Comment by vieditcom** [comment]
Looks like it's time to fix this gem to work with Rails 6...

**Comment by pikitgb** [comment]
@vieditcom @alphabt @6temes 

You might want to:
#1 migrate your rails version to 6.1.3.1, (6.0.2 didn't work for me)
#2 check if there is any issues related to the master.key or credentials 
```
rake aborted!
ActiveSupport::MessageEncryptor::InvalidMessage: ActiveSupport::MessageEncryptor::InvalidMessage
```
if #2 is this is the case, 
then delete your encrypted credentials 

`$ rm config/credentials.yml.enc`

and run this

`$ EDITOR="vi " bin/rails credentials:edit`

after that running  ​`$ rake traceroute --trace` should display your "Unused routes" w/o problem.

**Comment by 6temes** [comment]
Thanks! Now it works for me as well.
